version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - '.:/usr/src/app'
    ports:
      - 8004:8000